### ISSUE TITLE
Support running in docker container

### ISSUE THREAD

**Issue by LinuxDevon** [sublimelsp/LSP-clangd#13]
So I am wanting to run clangd from a docker container that uses my cross compiler. The paths are all based on the image so it makes it difficult to run from the local machine and doesn't find all the system files. Is it possible to do this already? I remember before when it wasn't a dedicated supported plugin I could overwrite the command but that doesn't seem to be working now. 

Two options I see being helpful one that lets me do `custom` binary option and just set it to whatever. The other is `docker` binary option but not sure how that looks. 

Any suggestions are greatly appreciated. Thank you for your help!

**Comment by LDAP** [comment]
Its already supported, see #11

**Comment by LinuxDevon** [comment]
Sorry for the overlap ask... For some reason when I searched the Issues it didn't show me this one :question:. Either way thank you! So this isn't released yet right? I would need to point this plugin to the github. That explains why I didn't see the option in the settings. Are there plans to add how to use docker / override to the README before release?

**Comment by rchl** [comment]
Indeed it seems to not be released yet. @LDAP is your intention to handle something more before releasing or what is the hold up?

**Comment by rchl** [comment]
That said, I wonder if it will really work correctly, even when overriding binary. Maybe I don't fully understand the use case but I feel like there would need to be support for mapping paths between docker<=>local path in LSP that we don't have right now...

**Comment by LDAP** [comment]
> Indeed it seems to not be released yet. @LDAP is your intention to handle something more before releasing or what is the hold up?

We can release the new version. The intention was to test a bit more, since I didn't use the plugin much since the PR.
