### ISSUE TITLE
C++ popup is formatted poorly in Sublime Text

### ISSUE THREAD

**Issue by ns-osmolsky** [sublimelsp/LSP-clangd#15]
Sublime Text shows a popup that is poorly formatted given the following C++ member variable declaration:

```
ns_event_t *m_eventMsg{nullptr};
```

The syntax above is C++11 and is (nearly) equivalent to `m_eventMsg = nullptr;`. Sublime shows that initialization but with extra line breaks… it thinks that it’s a block.

![78c18219e01e19756deb0c9f165167b7f0348c81](https://github.com/sublimelsp/LSP-clangd/assets/63256763/8c3b71c6-5616-47ed-857d-b3e3c3d1867e)

I think this data comes from `clangd` via LSP.

**Comment by predragnikolic** [comment]
Yes, that data is coming from the server(clangd).

Feel free to open an issue at clangd,
I will choose this, because we cannot do anything regarding that on the client(LSP-clangd).
