### ISSUE TITLE
Unhelpful return type decoding in tooltip

### ISSUE THREAD

**Issue by Protoster** [sublimelsp/LSP-clangd#18]
When hovering over a function identifier in a C source file, the tooltip will sometimes decode the typedefs of a return type and NOT show the declared type:
![Screenshot 2023-09-11 143734](https://github.com/sublimelsp/LSP-clangd/assets/5383872/b46a4772-cb97-4b3c-b254-62d20177bd1c)
(LSP is able to find the definition with no problems, where it is declared as `size_t`, not `unsigned long long`)

In other cases, it shows (in this function I declared) both the declared type and the decoded typedef:
![Screenshot 2023-09-11 143908](https://github.com/sublimelsp/LSP-clangd/assets/5383872/bad175dd-7159-4e2d-8893-d60ad3be650a)

When I'm looking up a declaration of a function, I'd like to see the declared type, rather than the typedef that's specific for my system.
I think it should work as shown in the second screenshot.

**Comment by rwols** [comment]
This sounds like you want the language server to change behavior, in which case I recommend to make a feature request at https://github.com/clangd/clangd/issues

**Comment by Protoster** [comment]
I see. This might be a problem because I don't know the internals of this plugin, so I won't be able to express the issue in terms of the clangd project. If I show them screenshots from the LSP-clangd plugin, they are likely to kindly tell me to open an issue here 😅

**Comment by rchl** [comment]
This output is coming from clang. If you show them those screenshots they will know that this package or the editor has nothing to do with the output.
