### ISSUE TITLE
Link highlight style setting stopped working recently

### ISSUE THREAD

**Issue by photex** [sublimelsp/LSP-clangd#21]
Hello!

I'm trying to figure whether I've done something wrong, if my theme is doing something wrong, or whether a recent version of LSP-clangd has a refression.
I prefer not to have all my include statements underlined, and `"link_highlight_style": "none",` no longer seems to have any effect.
I've set this globally and in my project settings to no avail. I'd really appreciate some advice on how to figure this out.

Thanks!

**Comment by photex** [comment]
Oh, now I'm also noticing that `"show_diagnostics_count_in_view_status": true,` is also not having any effect.

**Comment by rchl** [comment]
Those settings should be set in the LSP and not LSP-clang settings.

If that still doesn't work then post the output of "LSP: Troubleshoot server" command

**Comment by photex** [comment]
Oh... yes, my apologies. I just restarted sublime, LSP updated, I restarted again and now it's working. Sorry to bother you!
