### ISSUE TITLE
Add option to apply all fix-its or add fix-on-save options 

### ISSUE THREAD

**Issue by fruffy** [sublimelsp/LSP-clangd#25]
Some Sublime LSP services have an option to apply all fixes on save or with a command, for example ESLint: 
https://github.com/sublimelsp/LSP-eslint?tab=readme-ov-file#faq

Is something like this also possible for clangd? How much work would it be to implement it?

**Comment by LDAP** [comment]
Code actions are provided by the server. The correct place to ask is here: https://github.com/clangd/clangd/issues

**Comment by rwols** [comment]
https://github.com/clangd/clangd/issues/1446

**Comment by fruffy** [comment]
Thanks for the quick reply!
