### ISSUE TITLE
formatting instructions ignored

### ISSUE THREAD

**Issue by kendfss** [sublimelsp/LSP-clangd#3]
I'm writing wrt the guide at:

instructions saved in `.clang-format` were ignored.
Then I tried the settings file. first:
```json
        "clangd.fallback-style": "{IndentWidth: 4}", // as per command line style (I received type warnings when trying to enter in regular object notation)
```
then:
```json
"command": [
        "/usr/bin/clangd",
        "-i",
        "-style='{IndentWidth: 4}'"
    ]
```

To no avail.
The following (at the command-line) works fine though:
```bash
clangd -i -style='{IndentWidth: 4}' main.c
```

What am I doing wrong?
What else should I try?

**Comment by rchl** [comment]
`.clang-format` should probably still work though? The issue you've linked doesn't seem to say anything about that.

The output of `LSP: Troubleshoot server` might help to analyze that (assuming that `.clang-format` should work).

**Comment by kendfss** [comment]
It didn't work until I put it under `/`. This is fine for me because I don't use this server for anything other than small personal projects, but I assume it won't be ideal for people looking to alternate between/contribute to larger ones. I never checked the output (assuming it isn't automatically printed into the sublime terminal). I'll check it out later this week though.
