### ISSUE TITLE
'.clang-format' not respected

### ISSUE THREAD

**Issue by selimanac** [sublimelsp/LSP-clangd#34]
I got '.clang-format' at project root, system root, every root you can image :)
What ever I try, never get '.clang-format' working. LSP-clangd never respects styles from this file. 

Also `clangd.fallback-style`doesn't work either. I have this:
```
"clangd.fallback-style": "{ColumnLimit:0}",
```
but still got column breaks. I can't stop line breaks what ever I do.

Is this is a know issue, am I missing something?

Using: macOS 14.6.x, Sublime Text 4180

Thank you

**Comment by LDAP** [comment]
I use it all the time. Can you post your format file, LSP and LSP-clangd config, logs from the ST console and the LSP panel?

**Comment by selimanac** [comment]
> I use it all the time.

You might be right. The problem could be on my side, but I can't find it, and it's driving me crazy. I'd be so grateful if you could help me out.

> Can you post your format file

Currently, I'm working with Box2D, so the format file I'm using is [this one](https://github.com/erincatto/box2d/blob/main/.clang-format). I also changed the ColumnLimit: 0 to test if that was the issue, but no luck.

I'm expecting the same results as the code in this project. here are a few examples...

**Before**:
![Screenshot 2024-09-12 at 15 10 40](https://github.com/user-attachments/assets/7df7a34d-9d22-4490-a25c-0001c98a7464)

![Screenshot 2024-09-12 at 15 11 29](https://github.com/user-attachments/assets/f045a5be-1f79-4199-83bf-a1052012232a)

**After save**(lsp_format_on_save): 
![Screenshot 2024-09-12 at 15 10 53](https://github.com/user-attachments/assets/005cf103-888f-4a97-8689-ceff64d4efda)

![Screenshot 2024-09-12 at 15 11 37](https://github.com/user-attachments/assets/8ec3c28d-496c-4988-8ad0-bb4ef668463e)

> LSP and LSP-clangd config

They are very basic 

```json
{
	"show_diagnostics_panel_on_save": 1,
	"lsp_format_on_save": true,
	"lsp_format_on_paste": false,
	"lsp_code_actions_on_save": {
		"source.fixAll": true,
		"source.organizeImports": true,
		"source.fixAll.ts": true,
		"source.fixAll.eslint": true,
		"source.removeUnused.ts": false,
		"source.organizeImports.ts": false
	},
	"show_inlay_hints": true,
	"show_references_in_quick_panel": true
}
```

```json

{
	"initializationOptions": {
		"fallbackFlags": [
			"-fno-diagnostics-column"
		],
		"clangd.fallback-style": "{ColumnLimit:0}",
		"custom_command": [
			"-fno-diagnostics-column"
		],
	},
	"selector": "source.c | source.c++ | source.objc | source.objc++ | source.cuda-c++ | source.glsl | source.fp  | source.vp",
}

```

LSP log(only includes lsp_format_on_save action): 

[lsp.log.zip](https://github.com/user-attachments/files/16979211/lsp.log.zip)

ST console log

[st.log](https://github.com/user-attachments/files/16979265/st.log)

Thank you

**Comment by selimanac** [comment]
I fixed this by using latest llvm (since macos got older version) and setting it manually.
Thank you.
